# Use official Odoo 14 image
FROM odoo:14.0

# Set working directory
WORKDIR /mnt/extra-addons

# Copy your custom module into Odoo addons
COPY ./addons/your_custom_module /mnt/extra-addons/your_custom_module

# Expose Odoo default port
EXPOSE 8069
